import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Geologica } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import ThemeProvider from '@/providers/theme-provider';

import './globals.scss';

const workSans = Geologica({
  variable: '--font-geologica',
  weight: ['400', '500', '700', '800', '900'],
  style: 'normal',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${workSans.variable} antialiased`}>
        <ThemeProvider>
          <SessionProvider
            refetchInterval={0}
            refetchOnWindowFocus={false}
          >
            <AntdRegistry>{children}</AntdRegistry>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
