(create-category "Благоустройство")
(create-category "Бытовая техника, электроника")
(create-category "Галантерея")
(create-category "Детская одежда")
(create-category "Детские товары")
(create-category "Другие товары")
(create-category "Зоотовары")
(create-category "Инструменты")
(create-category "Мебель")
(create-category "Медицинские изделия")
(create-category "Обувь")
(create-category "Одежда")
(create-category "Оптические приборы")
(create-category "Отдых")
(create-category "Продукты питания")
(create-category "Промышленное оборудование")
(create-category "Религиозные и ритуальные товары")
(create-category "Сельское хозяйство")
(create-category "Системы охраны и безопасности")
(create-category "Спортивные товары")
(create-category "Строительство и ремонт")
(create-category "Сырье, полезные ископаемые")
(create-category "Текстиль")
(create-category "Товары для дома")
(create-category "Товары личного потребления")
(create-category "Торговое оборудование")
(create-category "Транспорт, техника, запчасти")
(create-category "Химическая промышленность")
(create-category "Электротовары")
(create-category "Ювелирные изделия, подарки")


(create-organization "Dildos" "Test one" "Pushkina 84" "480317480" nil)
(create-organization "RIK" "Sample" "Lenina 41" "129317480" nil)


(create-item "roga" 30 2)
(create-item "kopita" 30 2)
(create-item "dildo1" 25 1)
(create-item "dildo2" 25 1)
(create-item "dildo-small" 5 1)
                     
